[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[context.staging.environment]
  REACT_APP_API_URL = "https://ai-fit-room-1.onrender.com"
  REACT_APP_SOCKET_URL = "https://ai-fit-room-1.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
