[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://ai-fit-room.onrender.com"
  REACT_APP_SOCKET_URL = "https://ai-fit-room.onrender.com"
  REACT_APP_SEGMENTATION_URL = "https://ai-fit-room-9jfn.onrender.com"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://ai-fit-room.onrender.com"
  REACT_APP_SOCKET_URL = "https://ai-fit-room.onrender.com"
  REACT_APP_SEGMENTATION_URL = "https://ai-fit-room-9jfn.onrender.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://ai-fit-room.onrender.com"
  REACT_APP_SOCKET_URL = "https://ai-fit-room.onrender.com"
  REACT_APP_SEGMENTATION_URL = "https://ai-fit-room-9jfn.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
